version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_collaboration_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: asdfjkl
      POSTGRES_DB: collaboration_db